export const SERVER_URL = 'http://localhost:3001';

export const GET_ARTICLES = 'GET_ARTICLES';

export const GET_ARTICLE_STARTED = 'GET_ARTICLE_STARTED';
export const GET_ARTICLE_FAILED = 'GET_ARTICLE_FAILED';
export const GET_ARTICLE_COMPLETED = 'GET_ARTICLE_COMPLETED';

export const GET_ARTICLES_STARTED = 'GET_ARTICLES_STARTED';
export const GET_ARTICLES_FAILED = 'GET_ARTICLES_FAILED';
export const GET_ARTICLES_COMPLETED = 'GET_ARTICLES_COMPLETED';
